### ISSUE TITLE
No dependency updates found in PR

### ISSUE THREAD

**Issue by wobsoriano** [StafflinePeoplePlus/dependabot-changesets#8]
Hi! I'm encountering an issue while trying to use this action with [my repo](https://github.com/wobsoriano/svelte-clerk/blob/main/.github/workflows/dependabot-sync.yml) to update my Dependabot PRs with changesets.

Currently, I'm manually triggering the action by adding/removing labels to an existing Dependabot PR, such as [this one](https://github.com/wobsoriano/svelte-clerk/pull/44). I'm using the built-in github token (`secrets.GITHUB_TOKEN`), but I'm receiving [this error](https://github.com/wobsoriano/svelte-clerk/actions/runs/11037660199/job/30659067646?pr=44):

`No dependency updates found in PR` (even though there are actually version updates...)

Am I missing something in my setup or configuration? Thank you!

**Comment by jamesbirtles** [comment]
hopefully should be fixed in [0.1.4](https://github.com/StafflinePeoplePlus/dependabot-changesets/releases/tag/v0.1.4)

**Comment by wobsoriano** [comment]
Error gone, but still "no dependency updates found in this PR" :(

<img width="966" alt="Screenshot 2024-09-27 at 7 29 51 AM" src="https://github.com/user-attachments/assets/bd6edf28-cfc3-4189-9bcd-3ee4dab5a0f7">


<img width="558" alt="Screenshot 2024-09-27 at 7 18 32 AM" src="https://github.com/user-attachments/assets/470b9257-cc5c-48e8-9495-da40326122ce">

https://github.com/wobsoriano/svelte-clerk/actions/runs/11072325832/job/30766283687

**Comment by wobsoriano** [comment]
I have it in another repo too, this time the updates are in a tabular form, and it says "no dependency updates found in PR" too

<img width="920" alt="Screenshot 2024-09-27 at 7 29 11 AM" src="https://github.com/user-attachments/assets/aeaf7bcd-1809-42d1-a04c-bc25117bf63c">


PR: https://github.com/wobsoriano/vue-clerk/pull/163
Action: https://github.com/wobsoriano/vue-clerk/actions/runs/11072480250/job/30766781042

@fossamagna sorry for tagging you here but where you able to make it work?

**Comment by fossamagna** [comment]
@wobsoriano 
> @fossamagna sorry for tagging you here but where you able to make it work?

I hava a same issue. I can not make it work too.

Action: https://github.com/purpom-media-lab/amplify-data-migration/actions/runs/11072705914/job/30767608285?pr=19

**Comment by wobsoriano** [comment]
It works now, ty!
